[Adapters]
    [Adapters.Primary]
        [Adapters.Primary.HttpAdapter]
            [Adapters.Primary.HttpAdapter.Server]
                Port = ":8080"
            [Adapters.Primary.HttpAdapter.Router]
                [Adapters.Primary.HttpAdapter.Router.Shutdown]
                    Duration = 15
                [Adapters.Primary.HttpAdapter.Router.Timeout]
                    Duration = 60

    [Adapters.Secondary]
        [Adapters.Secondary.OpenVPN]
            BaseDir = "/data/openvpn/server"
            OutputDir = "/data/openvpn/clients"
            ScriptPath = "./openvpn-install.sh"
